import React from "react";
import { Loader, FormField, Card } from "../components";

const Home = () => {
  return (
    <section>
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          The community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">
          Browse through a celebration of imaginative and visually stunning
          images generated by DALL _E AI
        </p>
      </div>
      <div>
        <FormField />
      </div>
      <div>
        {/* <Loader /> */}
        <Card />
      </div>
    </section>
  );
};

export default Home;
